; PiSim Custom Project Editor User Settings
; Bu dosya, projeyi acan tum kullanicilar icin ozellestirilmis sade editor arayuzunu kilitler.

[/Script/UnrealEd.EditorPerProjectUserSettings]
bDisplayDocumentationLink=False
bDisplayActionListItemRefIds=False

[/Script/UnrealEd.LevelEditorViewportSettings]
bDrawGizmos=False
bDrawSnappingToolbar=False
bDrawCameraSpeed=False
bShowViewportControls=False
bShowTransformWidget=False

[/Script/LevelEditor.LevelEditorViewportSettings]
bDrawGizmos=False
bDrawSnappingToolbar=False
bDrawCameraSpeed=False
bShowViewportControls=False
